---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# LCtesterror

<!-- badges: start -->

<!-- badges: end -->

The goal of LCtesterror is to estimate true prevalence from test data accounting for unknown test error.

## Installation

You can install the development version of LCtesterror from [GitHub](https://github.com/) with:

``` r
# install.packages("pak")
pak::pak("bristol-vaccine-centre/LCtesterror")
```
<!-- Need to render `README.Rmd` regularly, to keep `README.md` up-to-date. `devtools::build_readme()` is handy for this. 
If adding plots need to commit and push resulting figure files, so they display on GitHub and CRAN.
-->

## Example

Example:

```{r example, eval = interactive(), message=FALSE, warning=FALSE}
library(LCtesterror)
 # Example (no test dependence, delay, or time included)
 # Simulate data
 sim_data <- sim.test.data(sim_size = 3000)
 # Simulated input parameters
 print(sim_data$test_parameters)
 # Simulated test data
 print(head(sim_data$test_parameters))

# Run LC model using simulated test results to correct prevalence for test error
 fit <- run.LC.model(sim_data$test_results, num_tests = 4,
                       data_ID = "sim", model_name = "basic_sim",
                      dependency_groups = NULL, covariates = NULL,
                      iter=1000, chains=2, warmup=500)

 # View estimated prevalence, sens and spec, and traceplots
 print(fit$prev_mean)
 print(fit$median_sens_spec_table)
 print(fit$traceplots)
 
```


```{r, echo=FALSE}
# Get and print the version of LCtesterror
cat("Using LCtesterror version:", as.character(packageVersion("LCtesterror")))

